id: A94C011E9
title: 'The Vision: A Prayer to Ārya Avalokiteśvara'
type: translation
pechas:
- I41FB33AF
- I48291CBB
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:43:57.894186
  last_modified_at: 2023-01-04 12:43:57.894206
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I41FB33AF/B6CC: E2BB
  I48291CBB/19DF: E2BB
